import type { CapacitorConfig } from '@capacitor/cli'

// Capacitor wraps the SAME web build (dist/) in a native Android / iOS shell.
// The web app on Cloudflare Pages is untouched by this file — it only matters
// when `npx cap sync` copies dist/ into android/ and ios/. See docs/HANDOFF.md.
//
// Native-only behaviour (camera, local notifications, system browser) lives in
// src/native/ and is guarded by Capacitor.isNativePlatform(), so the web build
// keeps its file inputs, .ics downloads and plain links.

const BRAND_BLUE = '#0669ac'

const config: CapacitorConfig = {
  appId: 'org.ohiohouserabbitrescue.app',
  appName: 'OHRR',
  webDir: 'dist',
  server: {
    // Serve the app from https://localhost on Android (instead of the default
    // http://) so Web Crypto, secure cookies and Supabase auth behave exactly
    // like the deployed site. Note: changing this later wipes app storage on
    // devices that already installed a build (different origin).
    androidScheme: 'https',
  },
  android: {
    // Test builds only — Play Console still needs a *signed* bundle.
    // Signing is done with the test keystore documented in docs/HANDOFF.md.
    allowMixedContent: false,
  },
  ios: {
    contentInset: 'automatic',
  },
  plugins: {
    SplashScreen: {
      // Shown by the native layer until React has painted; src/native/platform.ts
      // hides it after the first render so there's never a white flash.
      launchAutoHide: false,
      backgroundColor: BRAND_BLUE,
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      splashFullScreen: false,
      splashImmersive: false,
    },
    StatusBar: {
      // Light (white) icons over the brand-blue top bar.
      style: 'DARK',
      backgroundColor: BRAND_BLUE,
      overlaysWebView: false,
    },
    LocalNotifications: {
      // Small (status bar) icon on Android — must be a white-on-transparent
      // drawable; generated by @capacitor/assets alongside the launcher icon.
      smallIcon: 'ic_stat_ohrr',
      iconColor: BRAND_BLUE,
    },
  },
}

export default config
