-- =============================================================
-- OHRR — Bookings: shifts and appointments, in-house
--
-- Replaces the SignUp.com links (Bunny Socialization, Buncare shifts), the
-- appointment request form and the bonding / clinic sign-ups with one engine:
--
--   booking_types   what can be booked (a shift or an appointment) and its
--                   rules: how long, how many people per time, how far ahead
--                   you must book, how many times a month, what to confirm
--   booking_slots   the actual times, generated by staff in bulk
--                   ("Saturdays and Sundays, noon–4, one hour each, 4 people")
--   bookings        who booked which slot; shifts confirm themselves,
--                   appointments wait for staff to confirm
--
-- People book without an account: name, email, phone. They get an on-screen
-- confirmation, a reminder for their phone, and a cancel link (a private
-- token). Staff with `bookings.manage` see the roster per day, confirm
-- appointments, check people in. Everything is enforced in the database.
--
-- Paste + Run in the Supabase SQL editor. Idempotent.
-- =============================================================

insert into permissions(key, area, description) values
 ('bookings.manage', 'Bookings', 'Set up bookable shifts & appointments, see rosters, confirm and check in')
on conflict (key) do nothing;
insert into permission_presets(preset, permission_key) values
 ('Volunteer Lead', 'bookings.manage'),
 ('Adoptions Coordinator', 'bookings.manage')
on conflict do nothing;

-- -------------------------------------------------------------
create table if not exists booking_types (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references organizations(id) on delete cascade,
  slug             text not null,
  name             text not null,
  kind             text not null default 'shift' check (kind in ('shift', 'appointment')),
  description      text,
  requirements     text,                 -- shown before booking; one line per requirement
  location         text,
  duration_min     int  not null default 60 check (duration_min between 5 and 720),
  capacity         int  not null default 1 check (capacity between 1 and 200),   -- default per slot
  max_party        int  not null default 1 check (max_party between 1 and 20),   -- people per booking
  min_lead_hours   int  not null default 0 check (min_lead_hours between 0 and 720),
  max_per_month    int  check (max_per_month is null or max_per_month between 1 and 31),
  confirm_mode     text not null default 'auto' check (confirm_mode in ('auto', 'staff')),
  ask_reason       text,                 -- optional question shown on the form ("Which rabbit?")
  attest_text      text,                 -- optional checkbox the person must tick
  is_published     boolean not null default true,
  sort_order       int not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (org_id, slug)
);
drop trigger if exists trg_booking_types_updated on booking_types;
create trigger trg_booking_types_updated before update on booking_types
  for each row execute function set_updated_at();

create table if not exists booking_slots (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organizations(id) on delete cascade,
  type_id     uuid not null references booking_types(id) on delete cascade,
  starts_at   timestamptz not null,
  ends_at     timestamptz not null,
  capacity    int not null default 1 check (capacity between 0 and 200),
  note        text,
  is_open     boolean not null default true,
  created_by  uuid references auth.users(id),
  created_at  timestamptz not null default now(),
  unique (type_id, starts_at),
  check (ends_at > starts_at)
);
create index if not exists idx_booking_slots_type_time on booking_slots(type_id, starts_at);

create table if not exists bookings (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references organizations(id) on delete cascade,
  slot_id       uuid not null references booking_slots(id) on delete cascade,
  type_id       uuid not null references booking_types(id) on delete cascade,
  name          text not null,
  email         text not null,
  phone         text,
  party_size    int  not null default 1 check (party_size between 1 and 20),
  answer        text,                    -- reply to ask_reason
  notes         text,
  attested      boolean not null default false,
  status        text not null default 'confirmed'
                check (status in ('requested', 'confirmed', 'cancelled', 'checked_in', 'no_show')),
  cancel_token  uuid not null default gen_random_uuid(),
  source        text,
  confirmed_by  uuid references auth.users(id),
  checked_in_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_bookings_slot on bookings(slot_id, status);
create index if not exists idx_bookings_email on bookings(org_id, email, created_at desc);
create unique index if not exists idx_bookings_token on bookings(cancel_token);
drop trigger if exists trg_bookings_updated on bookings;
create trigger trg_bookings_updated before update on bookings
  for each row execute function set_updated_at();

-- -------------------------------------------------------------
-- RLS: the public reads published types and open future slots; bookings are
-- private (people use their token; staff use the capability).
-- -------------------------------------------------------------
alter table booking_types enable row level security;
alter table booking_slots enable row level security;
alter table bookings      enable row level security;

drop policy if exists booking_types_public_select on booking_types;
create policy booking_types_public_select on booking_types for select using (is_published);
drop policy if exists booking_types_staff_select on booking_types;
create policy booking_types_staff_select on booking_types for select using (has_permission(org_id, 'bookings.manage'));
drop policy if exists booking_types_staff_write on booking_types;
create policy booking_types_staff_write on booking_types for all
  using (has_permission(org_id, 'bookings.manage')) with check (has_permission(org_id, 'bookings.manage'));

drop policy if exists booking_slots_public_select on booking_slots;
create policy booking_slots_public_select on booking_slots for select
  using (is_open and exists (select 1 from booking_types t where t.id = type_id and t.is_published));
drop policy if exists booking_slots_staff_select on booking_slots;
create policy booking_slots_staff_select on booking_slots for select using (has_permission(org_id, 'bookings.manage'));
drop policy if exists booking_slots_staff_write on booking_slots;
create policy booking_slots_staff_write on booking_slots for all
  using (has_permission(org_id, 'bookings.manage')) with check (has_permission(org_id, 'bookings.manage'));

drop policy if exists bookings_staff_select on bookings;
create policy bookings_staff_select on bookings for select using (has_permission(org_id, 'bookings.manage'));
drop policy if exists bookings_staff_update on bookings;
create policy bookings_staff_update on bookings for update
  using (has_permission(org_id, 'bookings.manage')) with check (has_permission(org_id, 'bookings.manage'));
drop policy if exists bookings_staff_delete on bookings;
create policy bookings_staff_delete on bookings for delete using (has_permission(org_id, 'bookings.manage'));

grant select on booking_types, booking_slots to anon, authenticated;
grant insert, update, delete on booking_types, booking_slots to authenticated;
grant select, update, delete on bookings to authenticated;

-- -------------------------------------------------------------
-- Public: open slots for a type, with how many places are left
-- -------------------------------------------------------------
create or replace function booking_slots_open(p_slug text, p_from timestamptz default now(), p_to timestamptz default now() + interval '60 days')
returns table (
  slot_id uuid, starts_at timestamptz, ends_at timestamptz, capacity int, taken int, note text
) language sql stable security definer set search_path = public as $$
  select s.id, s.starts_at, s.ends_at, s.capacity,
         coalesce((select sum(b.party_size)::int from bookings b
                    where b.slot_id = s.id and b.status in ('requested', 'confirmed', 'checked_in')), 0) as taken,
         s.note
    from booking_slots s
    join booking_types t on t.id = s.type_id
   where t.slug = p_slug and t.is_published and s.is_open
     and s.starts_at >= greatest(p_from, now() + make_interval(hours => t.min_lead_hours))
     and s.starts_at <= p_to
   order by s.starts_at;
$$;
grant execute on function booking_slots_open(text, timestamptz, timestamptz) to anon, authenticated;

-- -------------------------------------------------------------
-- Public: book a slot. Every rule lives here.
-- -------------------------------------------------------------
create or replace function book_slot(
  p_slot_id uuid, p_name text, p_email text, p_phone text,
  p_party int default 1, p_answer text default null, p_notes text default null,
  p_attested boolean default false, p_source text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  s booking_slots;
  t booking_types;
  v_taken int;
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_name  text := btrim(coalesce(p_name, ''));
  v_party int := greatest(1, coalesce(p_party, 1));
  v_month_count int;
  b bookings;
begin
  if v_name = '' then raise exception 'Please tell us your name.'; end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Please enter a valid email address.'; end if;

  select * into s from booking_slots where id = p_slot_id for update;
  if not found or not s.is_open then raise exception 'That time is no longer available.'; end if;
  select * into t from booking_types where id = s.type_id;
  if not t.is_published then raise exception 'That is not open for booking.'; end if;
  if s.starts_at < now() + make_interval(hours => t.min_lead_hours) then
    raise exception 'That time is too soon — please pick a later one.';
  end if;
  if v_party > t.max_party then raise exception 'Up to % per booking.', t.max_party; end if;
  if t.attest_text is not null and not coalesce(p_attested, false) then
    raise exception 'Please confirm the requirements first.';
  end if;

  select coalesce(sum(party_size), 0) into v_taken from bookings
   where slot_id = s.id and status in ('requested', 'confirmed', 'checked_in');
  if v_taken + v_party > s.capacity then raise exception 'That time just filled up — please pick another.'; end if;

  if exists (select 1 from bookings where slot_id = s.id and email = v_email and status in ('requested', 'confirmed', 'checked_in')) then
    raise exception 'You are already booked for that time.';
  end if;

  if t.max_per_month is not null then
    select count(*) into v_month_count from bookings b2
      join booking_slots s2 on s2.id = b2.slot_id
     where b2.type_id = t.id and b2.email = v_email
       and b2.status in ('requested', 'confirmed', 'checked_in')
       and date_trunc('month', s2.starts_at at time zone 'America/New_York')
         = date_trunc('month', s.starts_at at time zone 'America/New_York');
    if v_month_count >= t.max_per_month then
      raise exception 'The limit is % per month for % — thank you for wanting to do more!', t.max_per_month, t.name;
    end if;
  end if;

  insert into bookings (org_id, slot_id, type_id, name, email, phone, party_size, answer, notes, attested, status, source)
  values (t.org_id, s.id, t.id, v_name, v_email, nullif(btrim(coalesce(p_phone, '')), ''), v_party,
          left(coalesce(p_answer, ''), 500), left(coalesce(p_notes, ''), 2000), coalesce(p_attested, false),
          case when t.confirm_mode = 'staff' then 'requested' else 'confirmed' end, left(coalesce(p_source, ''), 20))
  returning * into b;

  return jsonb_build_object(
    'booking_id', b.id, 'status', b.status, 'cancel_token', b.cancel_token,
    'type_name', t.name, 'kind', t.kind, 'location', t.location,
    'starts_at', s.starts_at, 'ends_at', s.ends_at, 'party_size', b.party_size);
end $$;
grant execute on function book_slot(uuid, text, text, text, int, text, text, boolean, text) to anon, authenticated;

-- Public: look up / cancel with the private token from the confirmation.
create or replace function booking_by_token(p_token uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'booking_id', b.id, 'status', b.status, 'name', b.name, 'party_size', b.party_size,
    'type_name', t.name, 'kind', t.kind, 'location', t.location,
    'starts_at', s.starts_at, 'ends_at', s.ends_at)
  from bookings b join booking_slots s on s.id = b.slot_id join booking_types t on t.id = b.type_id
  where b.cancel_token = p_token;
$$;
grant execute on function booking_by_token(uuid) to anon, authenticated;

create or replace function cancel_booking(p_token uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  update bookings set status = 'cancelled'
   where cancel_token = p_token and status in ('requested', 'confirmed');
  return booking_by_token(p_token);
end $$;
grant execute on function cancel_booking(uuid) to anon, authenticated;

-- -------------------------------------------------------------
-- Staff: make many slots at once.
--   p_weekdays: 0 = Sunday … 6 = Saturday (ISO dow via extract(dow))
--   p_start / p_end: local Columbus times, e.g. '12:00' and '16:00'
-- Creates back-to-back slots of the type's duration; existing ones are kept.
-- -------------------------------------------------------------
create or replace function generate_booking_slots(
  p_type_id uuid, p_from date, p_to date, p_weekdays int[],
  p_start time, p_end time, p_capacity int default null, p_note text default null
) returns int language plpgsql security definer set search_path = public as $$
declare
  t booking_types;
  d date;
  tm time;
  v_start timestamptz;
  v_end   timestamptz;
  n int := 0;
begin
  select * into t from booking_types where id = p_type_id;
  if not found then raise exception 'No such booking type'; end if;
  if not has_permission(t.org_id, 'bookings.manage') then raise exception 'Not allowed'; end if;
  if p_to < p_from or p_to - p_from > 370 then raise exception 'Pick a range of up to a year.'; end if;
  if p_end <= p_start then raise exception 'The end time must be after the start time.'; end if;

  d := p_from;
  while d <= p_to loop
    if extract(dow from d)::int = any (p_weekdays) then
      tm := p_start;
      while tm + make_interval(mins => t.duration_min) <= p_end loop
        v_start := (d + tm) at time zone 'America/New_York';
        v_end   := v_start + make_interval(mins => t.duration_min);
        if v_start > now() then
          insert into booking_slots (org_id, type_id, starts_at, ends_at, capacity, note, created_by)
          values (t.org_id, t.id, v_start, v_end, coalesce(p_capacity, t.capacity), p_note, auth.uid())
          on conflict (type_id, starts_at) do nothing;
          if found then n := n + 1; end if;
        end if;
        tm := tm + make_interval(mins => t.duration_min);
      end loop;
    end if;
    d := d + 1;
  end loop;
  insert into audit_log(org_id, actor_user_id, action, target_type, target_id, detail)
  values (t.org_id, auth.uid(), 'bookings.slots_generated', 'booking_type', t.id::text,
          jsonb_build_object('from', p_from, 'to', p_to, 'created', n));
  return n;
end $$;
grant execute on function generate_booking_slots(uuid, date, date, int[], time, time, int, text) to authenticated;

-- Staff: the roster for a day range (every booking with its slot and type).
create or replace function booking_roster(p_org uuid, p_from timestamptz, p_to timestamptz)
returns table (
  booking_id uuid, status text, name text, email text, phone text, party_size int,
  answer text, notes text, attested boolean, created_at timestamptz,
  slot_id uuid, starts_at timestamptz, ends_at timestamptz, capacity int,
  type_id uuid, type_name text, type_slug text, kind text, confirm_mode text
) language sql stable security definer set search_path = public as $$
  select b.id, b.status, b.name, b.email, b.phone, b.party_size, b.answer, b.notes, b.attested, b.created_at,
         s.id, s.starts_at, s.ends_at, s.capacity,
         t.id, t.name, t.slug, t.kind, t.confirm_mode
    from bookings b
    join booking_slots s on s.id = b.slot_id
    join booking_types t on t.id = b.type_id
   where b.org_id = p_org and has_permission(p_org, 'bookings.manage')
     and s.starts_at >= p_from and s.starts_at < p_to
   order by s.starts_at, t.name, b.created_at;
$$;
grant execute on function booking_roster(uuid, timestamptz, timestamptz) to authenticated;

-- Staff: confirm / cancel / check in / no-show.
create or replace function set_booking_status(p_id uuid, p_status text)
returns void language plpgsql security definer set search_path = public as $$
declare
  b bookings;
begin
  select * into b from bookings where id = p_id;
  if not found then raise exception 'No such booking'; end if;
  if not has_permission(b.org_id, 'bookings.manage') then raise exception 'Not allowed'; end if;
  if p_status not in ('requested', 'confirmed', 'cancelled', 'checked_in', 'no_show') then raise exception 'Bad status'; end if;
  update bookings set
    status = p_status,
    confirmed_by = case when p_status = 'confirmed' then auth.uid() else confirmed_by end,
    checked_in_at = case when p_status = 'checked_in' then now() else checked_in_at end
  where id = p_id;
  insert into audit_log(org_id, actor_user_id, action, target_type, target_id, detail)
  values (b.org_id, auth.uid(), 'booking.' || p_status, 'booking', p_id::text, jsonb_build_object('name', b.name));
end $$;
grant execute on function set_booking_status(uuid, text) to authenticated;

-- How many appointments are waiting for a staff confirmation (dashboard badge).
create or replace function count_pending_bookings(p_org uuid)
returns int language sql stable security definer set search_path = public as $$
  select case when has_permission(p_org, 'bookings.manage')
              then (select count(*)::int from bookings b join booking_slots s on s.id = b.slot_id
                     where b.org_id = p_org and b.status = 'requested' and s.starts_at > now() - interval '1 day')
              else 0 end;
$$;
grant execute on function count_pending_bookings(uuid) to authenticated;

-- -------------------------------------------------------------
-- Seed the bookable things OHRR runs today (wording from the live site).
-- Staff generate the actual times from the app; nothing is bookable until
-- they do, and every field here is editable in the Bookings manager.
-- -------------------------------------------------------------
do $$
declare
  v_org uuid;
begin
  select id into v_org from organizations where name = 'Ohio House Rabbit Rescue' limit 1;
  if v_org is null then return; end if;

  insert into booking_types (org_id, slug, name, kind, description, requirements, location, duration_min, capacity, max_party, min_lead_hours, max_per_month, confirm_mode, attest_text, sort_order)
  values
  (v_org, 'bunny-socialization', 'Bunny Socialization', 'shift',
   'Sit in with the bunnies and help them learn to trust people again. Many of our bunnies come from situations with little human contact; your calm company gets them ready for adoption.',
   E'Must be at least 6 years old. Children 10 and under must be accompanied by an adult.\nA parent accompanying a child must sign up for a slot too — everyone in the building is counted.\nNo more than two 1-hour shifts per month, so as many people as possible can take part.',
   'OHRR Adoption Center · 5485 N. High Street, Columbus', 60, 4, 1, 2, 2, 'auto', null, 10),
  (v_org, 'buncare-shift', 'Buncare shift', 'shift',
   'Keep the bunnies happy and healthy — sweeping and cleaning, feeding pellets and hay, expanding pens, changing litter boxes and more.',
   E'Must be at least 18 years old.\nMust have volunteered for Bunny Socialization at least twice, on two separate days.\nMust have completed the 2-hour Buncare Orientation (email OHRR to arrange it).\nPlease book at least two hours before your shift so someone is there to let you in.',
   'OHRR Adoption Center · 5485 N. High Street, Columbus', 120, 2, 1, 2, null, 'auto',
   'I have done two Bunny Socialization shifts on separate days and completed the Buncare Orientation.', 20),
  (v_org, 'adoption-visit', 'Adoption appointment', 'appointment',
   'Adoptions are by appointment on Saturdays and Sundays. A two-hour visit: see how we house and feed our bunnies, then meet and — if it’s a match — adopt one. Pick a time and an adoption facilitator will confirm it with you.',
   E'Please send an adoption application first — the facilitator confirms your appointment once they have talked it through with you.
Bring everyone who lives with the rabbit, including any rabbit you already have (for a bunny date).',
   'OHRR Adoption Center · 5485 N. High Street, Columbus', 120, 1, 6, 24, null, 'staff',
   null, 30),
  (v_org, 'bonding-session', 'Bunny bonding session', 'appointment',
   'A supervised meet on neutral ground at the center, guided by our team, with next steps for bonding at home.',
   null, 'OHRR Adoption Center · 5485 N. High Street, Columbus', 60, 1, 4, 24, null, 'staff', null, 40)
  on conflict (org_id, slug) do nothing;

  -- Mobile vet clinic: hidden until OHRR has confirmed dates (Set up → tick "People can see and book this").
  insert into booking_types (org_id, slug, name, kind, description, location, duration_min, capacity, max_party, min_lead_hours, confirm_mode, ask_reason, is_published, sort_order)
  values (v_org, 'vet-clinic', 'Mobile vet clinic', 'appointment',
          'A rabbit-savvy vet visits OHRR on select weekends for nail trims, wellness checks and microchipping — by appointment.',
          'OHRR Adoption Center · 5485 N. High Street, Columbus', 30, 1, 1, 24, 'auto', 'Your rabbit’s name and what they need (nail trim, wellness check, microchip)', false, 50)
  on conflict (org_id, slug) do nothing;

  update booking_types set ask_reason = 'Which rabbit would you like to meet? (optional)'
   where org_id = v_org and slug = 'adoption-visit' and ask_reason is null;
  update booking_types set ask_reason = 'Tell us about your rabbit and what you’re looking for'
   where org_id = v_org and slug = 'bonding-session' and ask_reason is null;
end $$;
